baseURL = "https://watsup.cs.northwestern.edu/"
languageCode = "en-us"
title = "WatsUp CS"

# Temporary for development
theme = "blowfish"

# Main menu
[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Events'
pageRef = '/events'
weight = 20

[[menus.main]]
parent = "Events"
name = 'Test'
pageRef = '/events/test'
weight = 10

[[menus.main]]
name = 'Initiatives'
pageRef = '/initiatives'
weight = 30

[[menus.main]]
name = 'Resources'
pageRef = '/resources'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 50
